-- MySihat AI (Web version) database setup
CREATE DATABASE IF NOT EXISTS mysihat
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE mysihat;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS daily_steps (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  step_date DATE NOT NULL,
  steps INT NOT NULL DEFAULT 0,
  UNIQUE KEY uniq_user_date (user_id, step_date),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS meals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  meal_time DATETIME NOT NULL,
  meal_text VARCHAR(255) NOT NULL,
  estimated_kcal INT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS points_ledger (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  point_date DATE NOT NULL,
  points_earned INT NOT NULL DEFAULT 0,
  points_spent INT NOT NULL DEFAULT 0,
  reason VARCHAR(120) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
